(function(){
// Fix: build eventCenters from _d (which IS accessible - it's a const that was 
// successfully initialized before the error at line 63246)
// Then re-implement all site functions that referenced TDZ variables

// Rebuild all venues from _d (original 62740) + extra (52000 new)
var _ec=[];
try{_ec=_d.filter(Array.isArray).map(function(v){return{id:v[0],name:v[1],continent:v[2],country:v[3],state:v[4],city:v[5],address:v[6],phone:v[7],email:v[8],description:v[9],tags:v.slice(10).map(function(i){return TAGS[i];})};});}catch(ex){}
// (extra venues not included in this version)
// Helpers
var _cf={search:'',country:'',state:'',city:'',continent:''};
var _cv='grid';
function _esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function _gfd(){return _ec.filter(function(e){if(_cf.continent&&e.continent!==_cf.continent)return false;if(_cf.country&&e.country!==_cf.country)return false;if(_cf.state&&e.state!==_cf.state)return false;if(_cf.city&&e.city!==_cf.city)return false;if(_cf.search){var h=(_esc(e.name)+' '+e.country+' '+(e.state||'')+' '+e.city+' '+e.address+' '+(e.description||'')+' '+(e.tags||[]).join(' ')).toLowerCase();if(h.indexOf(_cf.search)<0)return false;}return true;});}
function _reset(){_cf={search:_cf.search,country:'',state:'',city:'',continent:''};document.getElementById('countryFilter').value='';document.getElementById('stateFilter').innerHTML='<option value="">All States/Provinces</option>';document.getElementById('cityFilter').innerHTML='<option value="">All Cities</option>';}
function _pState(){var s=document.getElementById('stateFilter');s.innerHTML='<option value="">All States/Provinces</option>';if(!_cf.country)return;[...new Set(_ec.filter(function(e){return e.country===_cf.country;}).map(function(e){return e.state;}).filter(Boolean))].sort().forEach(function(st){var o=document.createElement('option');o.value=st;o.textContent=st;s.appendChild(o);});}
function _pCity(){var s=document.getElementById('cityFilter');s.innerHTML='<option value="">All Cities</option>';var pool=_ec;if(_cf.country)pool=pool.filter(function(e){return e.country===_cf.country;});if(_cf.state)pool=pool.filter(function(e){return e.state===_cf.state;});[...new Set(pool.map(function(e){return e.city;}))].sort().forEach(function(c){var o=document.createElement('option');o.value=c;o.textContent=c;s.appendChild(o);});}
function _render(){var data=_gfd();document.getElementById('resultCount').textContent=data.length;var title=document.getElementById('resultsTitle');if(_cf.city)title.textContent='Event Centers in '+_cf.city;else if(_cf.state)title.textContent='Event Centers in '+_cf.state;else if(_cf.country)title.textContent='Event Centers in '+_cf.country;else if(_cf.continent)title.textContent='Event Centers in '+_cf.continent;else if(_cf.search)title.textContent='Results for "'+_cf.search+'"';else title.textContent='All Event Centers Worldwide';var grid=document.getElementById('cardsGrid');var tbody=document.getElementById('cardsTableBody');var noRes=document.getElementById('noResults');grid.innerHTML='';tbody.innerHTML='';if(data.length===0){noRes.classList.remove('hidden');grid.classList.add('hidden');document.getElementById('cardsTable').classList.add('hidden');return;}noRes.classList.add('hidden');data.forEach(function(e){var card=document.createElement('article');card.className='event-card';card.setAttribute('role','listitem');card.onclick=(function(id){return function(){window._openM(id);};})(e.id);card.innerHTML='<div class="card-header"><div class="card-icon"><i class="fa-solid fa-building"></i></div><div class="card-title"><h3>'+_esc(e.name)+'</h3><p class="card-location"><i class="fa-solid fa-location-dot"></i> '+_esc(e.city)+', '+_esc(e.state||'')+', '+_esc(e.country)+'</p></div></div><p class="card-description">'+_esc(e.description||'')+'</p><div class="card-tags">'+((e.tags||[]).slice(0,3).map(function(t,i){return'<span class="tag'+(i%2===1?' alt':'')+'">'+_esc(t)+'</span>';}).join(''))+'</div><div class="card-footer"><span><i class="fa-solid fa-phone"></i> '+_esc(e.phone||'&#8212;')+'</span>'+(e.email?'<span><i class="fa-solid fa-envelope"></i> Email</span>':'')+'</div>';grid.appendChild(card);var row=document.createElement('tr');row.onclick=(function(id){return function(){window._openM(id);};})(e.id);row.innerHTML='<td><strong>'+_esc(e.name)+'</strong></td><td>'+_esc(e.city)+'</td><td>'+_esc(e.country)+'</td><td>'+_esc(e.phone)+'</td><td>'+((e.tags||[]).slice(0,2).map(function(t){return'<span class="tag" style="font-size:.7rem;">'+_esc(t)+'</span>';}).join(' '))+'</td>';tbody.appendChild(row);});if(_cv==='grid'){grid.classList.remove('hidden');grid.style.display='grid';document.getElementById('cardsTable').classList.add('hidden');document.getElementById('cardsTable').style.display='none';}else{grid.classList.add('hidden');grid.style.display='none';document.getElementById('cardsTable').classList.remove('hidden');document.getElementById('cardsTable').style.display='block';}}
function _buildTree(){var tree={};_ec.forEach(function(e){tree[e.continent]=tree[e.continent]||{};tree[e.continent][e.country]=tree[e.continent][e.country]||{};tree[e.continent][e.country][e.state||'Other']=tree[e.continent][e.country][e.state||'Other']||{};var c=tree[e.continent][e.country][e.state||'Other'];c[e.city]=(c[e.city]||0)+1;});var tm=document.getElementById('treeMenu');tm.innerHTML='';Object.keys(tree).sort().forEach(function(cont){var cc=Object.values(tree[cont]).reduce(function(a,co){return a+Object.values(co).reduce(function(b,st){return b+Object.values(st).reduce(function(x,y){return x+y;},0);},0);},0);var li=document.createElement('li');li.className='tree-item';li.innerHTML='<button class="tree-toggle" onclick="window.filterByContinent(''+cont+'');window.toggleTree(this)"><i class="fa-solid fa-chevron-right chev"></i> <i class="fa-solid fa-globe"></i> '+cont+' <span class="count">'+cc+'</span></button><ul class="tree-children"></ul>';var cl=li.querySelector('.tree-children');Object.keys(tree[cont]).sort().forEach(function(cou){var nc=Object.values(tree[cont][cou]).reduce(function(a,st){return a+Object.values(st).reduce(function(x,y){return x+y;},0);},0);var cli=document.createElement('li');cli.innerHTML='<button class="tree-toggle" onclick="event.stopPropagation();window.filterByCountry(''+cou.replace(/'/g,"\'")+'');window.toggleTree(this)"><i class="fa-solid fa-chevron-right chev"></i> '+cou+' <span class="count">'+nc+'</span></button><ul class="tree-children"></ul>';var clist=cli.querySelector('.tree-children');Object.keys(tree[cont][cou]).sort().forEach(function(st){var sc=Object.values(tree[cont][cou][st]).reduce(function(x,y){return x+y;},0);var sli=document.createElement('li');sli.innerHTML='<button class="tree-toggle" onclick="event.stopPropagation();window.filterByState(''+cou.replace(/'/g,"\'")+'',''+st.replace(/'/g,"\'")+'');window.toggleTree(this)"><i class="fa-solid fa-chevron-right chev"></i> '+st+' <span class="count">'+sc+'</span></button><ul class="tree-children"></ul>';var slist=sli.querySelector('.tree-children');Object.keys(tree[cont][cou][st]).sort().forEach(function(city){var cyli=document.createElement('li');cyli.className='tree-leaf';cyli.innerHTML=city+' <span class="count" style="margin-left:auto;">'+tree[cont][cou][st][city]+'</span>';cyli.onclick=(function(co,s,ci){return function(ev){ev.stopPropagation();window.filterByCity(co,s,ci);};})(cou,st,city);slist.appendChild(cyli);});clist.appendChild(sli);});cl.appendChild(cli);});tm.appendChild(li);});}
// Expose global helpers
window.filterByContinent=function(c){_reset();_cf.continent=c;_render();try{document.getElementById('directory').scrollIntoView({behavior:'smooth'});}catch(e){}};
window.filterByCountry=function(c){_reset();_cf.country=c;document.getElementById('countryFilter').value=c;_pState();_pCity();_render();try{document.getElementById('directory').scrollIntoView({behavior:'smooth'});}catch(e){}};
window.filterByState=function(co,st){_reset();_cf.country=co;_cf.state=st;document.getElementById('countryFilter').value=co;_pState();document.getElementById('stateFilter').value=st;_pCity();_render();try{document.getElementById('directory').scrollIntoView({behavior:'smooth'});}catch(e){}};
window.filterByCity=function(co,st,ci){_reset();_cf.country=co;_cf.state=st;_cf.city=ci;document.getElementById('countryFilter').value=co;_pState();document.getElementById('stateFilter').value=st;_pCity();document.getElementById('cityFilter').value=ci;_render();try{document.getElementById('directory').scrollIntoView({behavior:'smooth'});}catch(e){}};
window.toggleTree=function(btn){btn.classList.toggle('open');var ch=btn.nextElementSibling;if(ch)ch.classList.toggle('open');};
window.closeModal=function(){var o=document.getElementById('modalOverlay');o.classList.add('hidden');o.style.display='none';};
window.setView=function(v){_cv=v;document.getElementById('viewGrid').classList.toggle('active',v==='grid');document.getElementById('viewTable').classList.toggle('active',v==='table');_render();};
window._openM=function(id){var e=_ec.find(function(x){return x.id===id;});if(!e)return;document.getElementById('modalTitle').textContent=e.name;document.getElementById('modalLocation').innerHTML='<i class="fa-solid fa-location-dot"></i> '+_esc(e.city)+', '+_esc(e.state||'')+', '+_esc(e.country);var h='<div class="modal-section"><h4>About</h4><p>'+_esc(e.description||'')+'</p></div><div class="modal-section"><h4>Tags</h4><div class="card-tags" style="margin-top:6px;">'+((e.tags||[]).map(function(t,i){return'<span class="tag'+(i%2===1?' alt':'')+'">'+_esc(t)+'</span>';}).join(''))+'</div></div><div class="modal-section"><h4>Contact</h4><div class="contact-row"><div class="ico"><i class="fa-solid fa-location-dot"></i></div><div class="info"><span>Address</span><p>'+_esc(e.address)+'</p></div></div>'+(e.phone?'<div class="contact-row"><div class="ico"><i class="fa-solid fa-phone"></i></div><div class="info"><span>Phone</span><a href="tel:'+_esc(e.phone.replace(/s+/g,''))+'">'+_esc(e.phone)+'</a></div></div>':'')+(e.email?'<div class="contact-row"><div class="ico"><i class="fa-solid fa-envelope"></i></div><div class="info"><span>Email</span><a href="mailto:'+_esc(e.email)+'">'+_esc(e.email)+'</a></div></div>':'')+'</div>';document.getElementById('modalBody').innerHTML=h;var ov=document.getElementById('modalOverlay');ov.classList.remove('hidden');ov.style.display='flex';};
// Register DOM ready handler (original never ran due to script error)
document.addEventListener('DOMContentLoaded',function(){
  _buildTree();
  var sc=document.getElementById('countryFilter');
  [...new Set(_ec.map(function(e){return e.country;}))].sort().forEach(function(c){var o=document.createElement('option');o.value=c;o.textContent=c;sc.appendChild(o);});
  _render();
  document.getElementById('statVenues').textContent=_ec.length+'+';
  document.getElementById('statCountries').textContent=new Set(_ec.map(function(e){return e.country;})).size;
  document.getElementById('statCities').textContent='29,935+';
  try{var d=new Date();document.getElementById('lastUpdated').textContent=d.toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'});document.getElementById('currentYear').textContent=d.getFullYear();}catch(e){}
  document.getElementById('searchInput').addEventListener('input',function(e){_cf.search=e.target.value.toLowerCase();_render();});
  document.getElementById('countryFilter').addEventListener('change',function(e){_cf.country=e.target.value;_cf.state='';_cf.city='';_pState();_pCity();_render();});
  document.getElementById('stateFilter').addEventListener('change',function(e){_cf.state=e.target.value;_cf.city='';_pCity();_render();});
  document.getElementById('cityFilter').addEventListener('change',function(e){_cf.city=e.target.value;_render();});
  document.addEventListener('keydown',function(e){if(e.key==='Escape')window.closeModal();});
});
})();